// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercise_muscleGroups.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createExerciseMuscleGroups = `-- name: CreateExerciseMuscleGroups :exec
INSERT INTO exercise_muscle_groups (exercise_ID, muscle_groups_ID, primary_muscle, secondary_muscle, created_at, modified_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    NOW(),
    NOW()
)
`

type CreateExerciseMuscleGroupsParams struct {
	ExerciseID      uuid.UUID
	MuscleGroupsID  uuid.UUID
	PrimaryMuscle   sql.NullBool
	SecondaryMuscle sql.NullBool
}

func (q *Queries) CreateExerciseMuscleGroups(ctx context.Context, arg CreateExerciseMuscleGroupsParams) error {
	_, err := q.db.ExecContext(ctx, createExerciseMuscleGroups,
		arg.ExerciseID,
		arg.MuscleGroupsID,
		arg.PrimaryMuscle,
		arg.SecondaryMuscle,
	)
	return err
}
