// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Exercise struct {
	ID                    uuid.UUID
	Name                  string
	ExerciseType          string
	Equipment             string
	PrimaryMuscleGroups   pqtype.NullRawMessage
	SecondaryMuscleGroups pqtype.NullRawMessage
	Description           sql.NullString
	CreatedAt             sql.NullTime
	ModifiedAt            sql.NullTime
}

type User struct {
	ID         uuid.UUID
	FirstName  sql.NullString
	LastName   sql.NullString
	Email      string
	Password   string
	CreatedAt  sql.NullTime
	ModifiedAt sql.NullTime
}
