// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Exercise struct {
	ID                  uuid.UUID
	Name                string
	ExerciseType        string
	Equipment           string
	Description         sql.NullString
	HasPrimaryMuscles   sql.NullBool
	HasSecondaryMuscles sql.NullBool
	CreatedAt           sql.NullTime
	ModifiedAt          sql.NullTime
}

type ExerciseMuscleGroup struct {
	ID              int32
	ExerciseID      uuid.UUID
	MuscleGroupsID  uuid.UUID
	PrimaryMuscle   sql.NullBool
	SecondaryMuscle sql.NullBool
	CreatedAt       sql.NullTime
	ModifiedAt      sql.NullTime
}

type ExerciseSet struct {
	ID                uuid.UUID
	WorkoutExerciseid uuid.UUID
	Ordinal           int32
	Weight            float64
	Reps              sql.NullInt32
	StaticHoldTime    sql.NullInt32
	CreatedAt         sql.NullTime
	ModifiedAt        sql.NullTime
}

type MuscleGroup struct {
	ID          uuid.UUID
	BodyPart    string
	MuscleGroup string
	MuscleName  string
	CreatedAt   sql.NullTime
	ModifiedAt  sql.NullTime
}

type Plan struct {
	ID              uuid.UUID
	Name            string
	Goal            string
	Days            sql.NullInt32
	Duration        sql.NullString
	Description     sql.NullString
	ExperienceLevel sql.NullString
	CreatedAt       sql.NullTime
	ModifiedAt      sql.NullTime
}

type RefreshToken struct {
	Token     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	UserID    uuid.UUID
	ExpiresAt sql.NullTime
	RevokedAt sql.NullTime
}

type User struct {
	ID         uuid.UUID
	FirstName  sql.NullString
	LastName   sql.NullString
	Email      string
	Password   string
	CreatedAt  sql.NullTime
	ModifiedAt sql.NullTime
}

type UserExercise struct {
	ID             uuid.UUID
	Userid         uuid.UUID
	Exerciseid     uuid.UUID
	DeclineIncline sql.NullInt64
	CreatedAt      sql.NullTime
	ModifiedAt     sql.NullTime
}

type UserWorkout struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	WorkoutID  uuid.UUID
	CreatedAt  sql.NullTime
	ModifiedAt sql.NullTime
}

type Workout struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	ModifiedAt  sql.NullTime
}

type WorkoutBlock struct {
	ID                    uuid.UUID
	Ordinal               sql.NullInt32
	Workoutid             uuid.UUID
	RestsecondsAfterBlock sql.NullInt32
	CreatedAt             sql.NullTime
	ModifiedAt            sql.NullTime
}

type WorkoutExercise struct {
	ID             uuid.UUID
	Ordinal        sql.NullInt32
	WorkoutBlockid uuid.UUID
	Exerciseid     uuid.UUID
	Notes          sql.NullString
	CreatedAt      sql.NullTime
	ModifiedAt     sql.NullTime
}
