// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package database

import (
	"context"
	"database/sql"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (id, name, goal, days, duration, description, experience_level, created_at, modified_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    NOW(),
    NOW()
)
RETURNING id, name, goal, days, duration, description, experience_level, created_at, modified_at
`

type CreatePlanParams struct {
	Name            string
	Goal            string
	Days            sql.NullInt32
	Duration        sql.NullString
	Description     sql.NullString
	ExperienceLevel sql.NullString
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRowContext(ctx, createPlan,
		arg.Name,
		arg.Goal,
		arg.Days,
		arg.Duration,
		arg.Description,
		arg.ExperienceLevel,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Goal,
		&i.Days,
		&i.Duration,
		&i.Description,
		&i.ExperienceLevel,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
