// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: workouts.sql

package database

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createWorkOut = `-- name: CreateWorkOut :one
INSERT INTO workouts (id, name, description, exercises, created_at, modified_at)
Values(
    gen_random_uuid(),
    $1,
    $2,
    $3,
    NOW(),
    NOW()
)
RETURNING id, name, description, exercises, created_at, modified_at
`

type CreateWorkOutParams struct {
	Name        string
	Description sql.NullString
	Exercises   pqtype.NullRawMessage
}

func (q *Queries) CreateWorkOut(ctx context.Context, arg CreateWorkOutParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, createWorkOut, arg.Name, arg.Description, arg.Exercises)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Exercises,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
