services:
  psql_wb:
    image: postgres:18-alpine3.22
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${WORKOUTBUILDER_DB_USERNAME}
      POSTGRES_PASSWORD: ${WORKOUTBUILDER_DB_PASSWORD}
      POSTGRES_DB: ${WORKOUTBUILDER_DB_DATABASE}
    ports:
      - ${DEVICE_PORT}:${WORKOUTBUILDER_DB_PORT}
    volumes:
      - psql_volume_wb:/var/lib/postgresql/data

volumes:
  psql_volume_wb:
