services:
  psql_wp:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${WORKOUTBUILDER_DB_DATABASE}
      POSTGRES_USER: ${WORKOUTBUILDER_DB_USERNAME}
      POSTGRES_PASSWORD: ${WORKOUTBUILDER_DB_PASSWORD}
    ports:
      - "${WORKOUTBUILDER_DB_PORT}"
    volumes:
      - psql_volume_wb:/var/lib/postgresql/data

volumes:
  psql_volume_wb: